//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CimscoPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageType
    {
        public MessageType()
        {
            this.PortalMessages = new HashSet<PortalMessage>();
        }
    
        public int MessageTypeId { get; set; }
        public string TypeName { get; set; }
        public string TypeElement { get; set; }
    
        public virtual ICollection<PortalMessage> PortalMessages { get; set; }
    }
}
