//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CimscoPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageCategory
    {
        public MessageCategory()
        {
            this.PortalMessages = new HashSet<PortalMessage>();
        }
    
        public int MessageCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Element1 { get; set; }
        public string Element2 { get; set; }
    
        public virtual ICollection<PortalMessage> PortalMessages { get; set; }
    }
}
