//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CimscoPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageType
    {
        public MessageType()
        {
            this.MessageFormats = new HashSet<MessageFormat>();
        }
    
        public int MessageTypeId { get; set; }
        public string Description { get; set; }
        public string PageElement { get; set; }
    
        public virtual ICollection<MessageFormat> MessageFormats { get; set; }
    }
}
